{"name": "Проверка логина с неверным логином и паролем", "status": "passed", "description": "Авторизуемся под пользователем, заполняя поле несуществующим логином/паролем. Получаем сообщение об ошибке \"email or password are incorrect\" и код 401", "steps": [{"name": "Создаем рандомного пользователя", "status": "passed", "start": 1720953943620, "stop": 1720953943620}], "start": 1720953943620, "stop": 1720953943882, "uuid": "22efa537-90b2-4b1b-93e8-73ff74cdd0b3", "historyId": "f406495bdfc7848394c95422c08a8930", "testCaseId": "f406495bdfc7848394c95422c08a8930", "fullName": "tests.test_login_user.TestLoginUsers#test_login_with_invalid_field_login_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUsers"}, {"name": "host", "value": "MBAirDmitry.local"}, {"name": "thread", "value": "73907-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}